name: echo

on:
  workflow_dispatch:

jobs:
  go-echo:
    name: release run
    runs-on: ubuntu-latest
    steps:
    
    - uses: tsanton/gohub-action@master
      with:
        tag: "0.1.8"
        message: "Eat pudding and fall asleep"
        name: "Tobias"
