name: test-invocate-reusable-action

on:
  workflow_dispatch:

jobs:
  go-echo:
    name: release run
    runs-on: ubuntu-latest
    steps:
    
    - uses: tsanton/gohub-action@0.1.11
      with:
        tag: "0.1.11"
        message: "Eat pudding and fall asleep"
        name: "Kjersti"
